### PR TITLE
Apply merge update to proper branch

### PR DESCRIPTION
**Pull request by bobjacobsen**
Merge this one instead of #20 please.

### CODE REVIEW

**Comment by bobjacobsen** [comment]
Fixes the conflicts in #19 once this has been merged into the `eb-jar-updates` branch, and then merged in JMRI/JMRI

**Comment by bobjacobsen** [comment]
Thanks.  That fixes the conflicts with JMRI/JMRI master in that PR.  Once the checks complete, I'll merge that, and then you can pick all that up into your master branch.  Should go OK.

**Comment by silverailscolo** [comment]
Great! I see lots of structural improvements happening to the help files; thanks for those too.

**Comment by bobjacobsen** [comment]
Thanks.  I've merged this branch into the main JMRI/JMRI master branch now, so you should be able to just pull from GitHub (e.g. `git checkout master; git pull` on the command line) to be back to consistent.  If not, let me know; we may have to revert #19 in that case after all, but we should consult first.

**Pull request merged**
